"""baseline schema

Revision ID: ebf0218d2367
Revises: 
Create Date: 2026-08-25 09:08:48.348670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # required by the JSONB variant below
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'ebf0218d2367'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_meal_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('breakfast_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lunch_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dinner_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_meal_rates_rate_date'), 'daily_meal_rates', ['rate_date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_registration_number'), 'users', ['registration_number'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('attendance_type', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_date', 'meal_type', name='uq_attendance')
    )
    op.create_index('ix_attendance_date', 'attendance', ['meal_date'], unique=False)
    op.create_index('ix_attendance_student_date_type', 'attendance', ['student_id', 'meal_date', 'meal_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('billing_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('opening_stock_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchases_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_stock_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('operational_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('administrative_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('chargeable_days', sa.Integer(), nullable=False),
    sa.Column('actual_food_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total_expense', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mess_daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unpublish_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_billing_period_month'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_billing_period_month_year')
    )
    op.create_index('ix_billing_period_year_month', 'billing_periods', ['year', 'month'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waived_by', sa.UUID(), nullable=True),
    sa.Column('waiver_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint("(status != 'WAIVED') OR (waived_at IS NOT NULL AND waived_by IS NOT NULL AND waiver_reason IS NOT NULL)", name='chk_fine_waiver'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_date', 'meal_type', name='uq_fine')
    )
    op.create_index('ix_fine_status', 'fines', ['status', 'student_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'meal_type', name='uq_holiday_per_meal')
    )
    op.create_index('uq_holiday_whole_day', 'holidays', ['holiday_date'], unique=True, postgresql_where=sa.text('meal_type IS NULL'))
    op.create_table('meal_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_date', 'meal_type', name='uq_meal_selection')
    )
    op.create_index('ix_meal_date', 'meal_selections', ['meal_date'], unique=False)
    op.create_index('ix_meal_student_date_type', 'meal_selections', ['student_id', 'meal_date', 'meal_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stock_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('physical_closing_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('physical_closing_qty >= 0', name='ck_stock_count_qty_non_negative'),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', 'item_id', name='uq_stock_count_period_item')
    )
    op.create_index('ix_stock_count_year_month', 'stock_counts', ['year', 'month'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mess_id', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('student_type', sa.String(length=20), nullable=False),
    sa.Column('campus_location', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('student_profiles')
    op.drop_index('ix_stock_count_year_month', table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notification_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_meal_student_date_type', table_name='meal_selections')
    op.drop_index('ix_meal_date', table_name='meal_selections')
    op.drop_table('meal_selections')
    op.drop_index('uq_holiday_whole_day', table_name='holidays', postgresql_where=sa.text('meal_type IS NULL'))
    op.drop_table('holidays')
    op.drop_index('ix_fine_status', table_name='fines')
    op.drop_table('fines')
    op.drop_index('ix_billing_period_year_month', table_name='billing_periods')
    op.drop_table('billing_periods')
    op.drop_index('ix_audit_target', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_student_date_type', table_name='attendance')
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_registration_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_daily_meal_rates_rate_date'), table_name='daily_meal_rates')
    op.drop_table('daily_meal_rates')
    # ### end Alembic commands ###
